<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFramework)</TargetFramework>
        <LangVersion>$(LangVersion)</LangVersion>
        <Nullable>$(Nullable)</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Store.DAL\Store.DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" />
    </ItemGroup>

</Project>
