<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFramework)</TargetFramework>
        <LangVersion>$(LangVersion)</LangVersion>
        <Nullable>$(Nullable)</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Store.DAL\Store.DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DataTransferObjects\Stores\Query\" />
    </ItemGroup>

</Project>
